# Generated by Django 3.1 on 2020-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200908_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_webdev_options',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
