# Generated by Django 3.1 on 2020-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_has_webdev_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_description',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
