# Generated by Django 3.1 on 2020-09-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_has_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='has_description',
            new_name='has_message',
        ),
    ]
