# Generated by Django 3.1 on 2020-09-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200908_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='has_message',
            new_name='has_user_message',
        ),
    ]
