# Generated by Django 3.1 on 2020-09-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200921_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='has_webdev_options',
        ),
    ]
