# Generated by Django 3.1 on 2020-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdevs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdev',
            name='description',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='webdev',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='webdev',
            name='repo_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='webdev',
            name='site_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
